TRANGADMIN/WebShop/Models/ctdh.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctdh
    {
        public int id_ctdh { get; set; }
        public Nullable<int> id_sanpham { get; set; }
        public Nullable<int> so_luong { get; set; }
        public Nullable<decimal> gia { get; set; }
        public Nullable<decimal> tong_tien { get; set; }
        public Nullable<int> id_donhang { get; set; }
    
        public virtual sanpham sanpham { get; set; }
        public virtual donhang donhang { get; set; }
    }
}

TRANGADMIN/WebShop/Areas/Admin/Controllers/QuanLyDonHangController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using WebShop.Models;

namespace WebShop.Areas.Admin.Controllers
{
	public class QuanLyDonHangController : Controller
	{
		thoitrangnamEntities4 db = new thoitrangnamEntities4();
		// GET: Admin/QuanLyDonHang
		public ActionResult Index(string searchString, int? page)
		{
			int pageSize = 5;
			int pageNumber = (page ?? 1);
			return View(db.donhangs.Where(n => n.user.ten_khach_hang.Contains(searchString) || searchString == null).ToList().OrderByDescending(n => n.id_user).ToPagedList(pageNumber, pageSize));
		}
		//Sua sp
		[HttpGet]
		public ActionResult Edit(int? id)
		{
			ViewBag.idtinhtrang = new SelectList(db.giaohangs.ToList().OrderBy(n => n.status), "id", "status");
			ViewBag.idthanhtoan = new SelectList(db.thanhtoans.ToList().OrderBy(n => n.status), "id", "status");
			//đưa dữ liệu vào dropdown list ten_chatlieu	ten_loaihang	ten_mau	ten_phanloai
			donhang sp = db.donhangs.SingleOrDefault(n => n.id_donhang == id);
			if (sp == null)
			{
				Response.StatusCode = 404;
				return null;
			}

			return View(sp);
		}
			
		[HttpPost]
		[ValidateInput(false)]
		public ActionResult Edit(donhang ph, FormCollection f)
		{
			var session = (user)Session["Taikhoan"];
			if (ModelState.IsValid)
			{
				//thuc hien gui mail
				MailMessage mm = new MailMessage("cskhbrazza123@gmail.com",session.mail);
				mm.Subject = "Xác nhận đơn hàng";
				mm.Body = "Đơn hàng đã được xác nhận";
				mm.IsBodyHtml = true;

				SmtpClient smtp = new SmtpClient();
				smtp.Host = "smtp.gmail.com";
				smtp.Port = 587;
				smtp.EnableSsl = true;

				NetworkCredential nc = new NetworkCredential("cskhbrazza123@gmail.com", "cskh123456");
				smtp.UseDefaultCredentials = true;
				smtp.Credentials = nc;
				smtp.Send(mm);
				// thay doi thanh da tra loi

				donhang dh = db.donhangs.SingleOrDefault(n=>n.id_donhang==ph.id_donhang);
				dh.idtinhtrang = 1;
				dh.idthanhtoan = ph.idthanhtoan;
				db.SaveChanges();
			}
			return RedirectToAction("Index");
		}
		//xem chi tiet don hang
		public ActionResult ctdh(int? iddh)
		{
			List<ctdh> ct = db.ctdhs.Where(n => n.id_donhang == iddh).ToList();
			return View(ct);
		}
		//xóa sp
		[HttpGet]
		public ActionResult Delete(int? id)
		{
			donhang sp = db.donhangs.SingleOrDefault(n => n.id_donhang == id);
			if (sp == null)
			{
				Response.StatusCode = 404;
				return null;
			}

			return View(sp);
		}

		[HttpPost, ActionName("Delete")]
		public ActionResult Delete(int id)
		{
			donhang sp = db.donhangs.SingleOrDefault(n => n.id_donhang == id);
			List<ctdh> ctdh = db.ctdhs.Where(n => n.id_donhang == id).ToList();
			if (sp == null)
			{
				Response.StatusCode = 404;
				return null;
			}
			foreach (var item in ctdh)
			{

				db.ctdhs.Remove(item);
			}
			db.donhangs.Remove(sp);
			db.SaveChanges();
			return RedirectToAction("Index");
		}
	}
}

TRANGADMIN/WebShop/Areas/Admin/Views/QuanLyDonHang/Delete.cshtml
@model WebShop.Models.donhang
@using WebShop.Models;
@{
	ViewBag.Title = "Delete";
	Layout = "~/Views/Layout/_LayoutAdmin.cshtml";
}
@{
	var session = (user)Session["Taikhoan"];
}
@if (session != null)
{
	<h2>Xóa đơn hàng</h2>

	<h3>Bạn có chắc là muốn xóa đơn hàng</h3>
	<div>
		<hr />
		<dl class="dl-horizontal">

			<dt>
				Tên khách hàng
			</dt>

			<dd>
				@Html.DisplayFor(model => model.user.tenuser)
			</dd>
			<dt>
				Địa chỉ
			</dt>

			<dd>
				@Html.DisplayFor(model => model.diachi)
			</dd>

			<dt>
				Ngày tạo hóa đơn
			</dt>

			<dd>
				@Html.DisplayFor(model => model.ngay_tao_hd)
			</dd>

			<dt>
				Số điện thoại
			</dt>

			<dd>
				@Html.DisplayFor(model => model.sdt)
			</dd>

			<dt>
				Tổng tiền
			</dt>

			<dd>
				@Html.DisplayFor(model => model.tong_tien)
			</dd>


			<dt>
				Tình trạng
			</dt>

			<dd>
				@Html.DisplayFor(model => model.giaohang.status)
			</dd>

			<dt>
				Thanh toán
			</dt>

			<dd>
				@Html.DisplayFor(model => model.thanhtoan.status)
			</dd>



		</dl>

		@using (Html.BeginForm())
		{
			@Html.AntiForgeryToken()

		<div class="form-actions no-color">
			<input type="submit" value="Xóa" class="btn btn-default" style="color:red; font-weight:bold"/> |
			@Html.ActionLink("Quay trở lại", "Index", "", new { @style = "color: black;padding:5px;font-weight: bold;", @class = "btn btn-default" })
		</div>
		}
	</div>
}
else
{
	<h2>Bạn chưa đăng nhập</h2>
	<a href="@Url.Action("Login","Login")">
		<p style="padding-bottom: 29px;color: blue;text-decoration: underline;">Trở lại đăng nhập</p>
	</a>
}

TRANGADMIN/WebShop/Areas/Admin/Views/QuanLyDonHang/Edit.cshtml
@model WebShop.Models.donhang
@using WebShop.Models;
@{
	ViewBag.Title = "Edit";
	Layout = "~/Views/Layout/_LayoutAdmin.cshtml";
}
@{
	var session = (user)Session["Taikhoan"];
}
@if (session != null)
{
	<h2>Xác nhận đơn hàng</h2>


	using (Html.BeginForm())
	{
		@Html.AntiForgeryToken()

		<div class="form-horizontal">
			<hr />
			@Html.ValidationSummary(true, "", new { @class = "text-danger" })
			@Html.HiddenFor(model => model.id_donhang)


			

			<div class="form-group">
				<label class="control-label col-md-2" for="idthanhtoan">Thanh toán</label>
				<div class="col-md-10">
					@Html.DropDownList("idthanhtoan", null, htmlAttributes: new { @class = "form-control" })
					@Html.ValidationMessageFor(model => model.idthanhtoan, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				<div class="col-md-offset-2 col-md-10">
					<input type="submit" value="Xác nhận" class="btn btn-default" />
				</div>
			</div>
		</div>
	}

		<div>
		
			@Html.ActionLink("Quay trở lại", "Index","", new { @style = "color: black;padding:5px;font-weight: bold;", @class = "btn btn-default" })
		</div>

	@section Scripts {
		@Scripts.Render("~/bundles/jqueryval")
	}
}
else
{
	<h2>Bạn chưa đăng nhập</h2>
	<a href="@Url.Action("Login","Login")">
		<p style="padding-bottom: 29px;color: blue;text-decoration: underline;">Trở lại đăng nhập</p>
	</a>
}

TRANGADMIN/WebShop/Areas/Admin/Views/QuanLyDonHang/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@model PagedList.PagedList<WebShop.Models.donhang>
@using WebShop.Models;


@{
	ViewBag.Title = "Index";
	Layout = "~/Views/Layout/_LayoutAdmin.cshtml";
}

@{
	var session = (user)Session["Taikhoan"];
}
@if (session != null)
{
<h2 style="
    font-weight: initial;
">Quản lý đơn hàng</h2>


<br />
using (Html.BeginForm("Index", "QuanLyDonHang", FormMethod.Get))
{
	@Html.TextBox("searchString")<input type="submit" value="Search" />
}
<br />
	<table class="table table-striped">
		<tr>
			<th>
				Tên khách hàng
			</th>
			<th>
				Địa chỉ
			</th>
			<th>
				SĐT
			</th>
			<th>
				Tổng tiền
			</th>
			<th>
				Ngày tạo hđ
			</th>
			<th>
				Tình trạng
			</th>
			<th>
				Thanh toán
			</th>
			<th>
				
			</th>
		</tr>

		@foreach (var item in Model)
		{
			<tr>
				<td>
					@Html.DisplayFor(modelItem => item.user.ten_khach_hang, new { @style = "width: 160px;" })
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.user.dia_chi1)
				</td>

				<td>
					@Html.DisplayFor(modelItem => item.user.sdt)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.tong_tien)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.ngay_tao_hd)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.giaohang.status)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.thanhtoan.status)
				</td>
				<td style="width:195px;">

					@Html.ActionLink("CTĐH", "ctdh", new { iddh = item.id_donhang }, new {@style= "color: black;padding:5px;font-weight: bold;", @class= "btn btn-default" }) 

					@Html.ActionLink("Xác nhận", "Edit", new { id = item.id_donhang }, new { @style = "color: black;padding:5px;font-weight: bold;", @class = "btn btn-default" })
					@Html.ActionLink("Xóa", "Delete", new { id = item.id_donhang }, new { @style = "color: red;padding:5px;font-weight: bold;", @class = "btn btn-default" })
				</td>
			</tr>
		}

	</table>

}
					else
					{
	<h2>Bạn chưa đăng nhập</h2>
	<a href="@Url.Action("Login","Login")">
		<p style="padding-bottom: 29px;color: blue;text-decoration: underline;">Trở lại đăng nhập</p>
	</a>
					}
@*Tạo link liên kết các trang*@
@if (session != null)
{
	<h7>Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/ @Model.PageCount</h7>
	<div class="MenuTrang">
		@Html.PagedListPager(Model, page => Url.Action("Index", "QuanLyDonHang", new { page, searchString = Request.QueryString["searchString"] }))
	</div>
	<style>
		.MenuTrang li {
			display: inline;
		}
	</style>

}
else
{
}

TRANGADMIN/WebShop/Areas/Admin/Views/QuanLyDonHang/ctdh.cshtml
@model IEnumerable<WebShop.Models.ctdh>
@using WebShop.Models;
@{
	ViewBag.Title = "ctdh";
	Layout = "~/Views/Layout/_LayoutAdmin.cshtml";
}
@{
	var session = (user)Session["Taikhoan"];
}
@if (session != null)
{
	<h2>Chi tiết đơn hàng</h2>


	<table class="table">
		<tr>
			<th>
				Thứ tự
			</th>
			<th>
				Tên sản phẩm
			</th>
			<th>
				Giá số lượng
			</th>
			<th>
				Số lượng
			</th>

			<th>
				Tổng tiền
			</th>
			<th></th>
		</tr>
		@{
			int i = 0;
		}

		@foreach (var item in Model)
		{
			i++;
			<tr>
				<td>
					@i
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.sanpham.ten_sp)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.gia)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.so_luong)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.tong_tien)
				</td>


			</tr>
		}

	</table>
	<div>

		@Html.ActionLink("Quay trở lại", "Index", "", new { @style = "color: black;padding:5px;font-weight: bold;", @class = "btn btn-default" })
	</div>

}
else
{
	<h2>Bạn chưa đăng nhập</h2>
	<a href="@Url.Action("Login","Login")">
		<p style="padding-bottom: 29px;color: blue;text-decoration: underline;">Trở lại đăng nhập</p>
	</a>
}