TRANGADMIN/WebShop/Areas/Admin/Controllers/QuanLyPhanLoaiController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using WebShop.Models;

namespace WebShop.Areas.Admin.Controllers
{
    public class QuanLyPhanLoaiController : Controller
    {
        thoitrangnamEntities4 db = new thoitrangnamEntities4();
        // GET: Admin/QuanLyUser
        public ActionResult Index(string searchString, int? page)
        {
            //Phan trang
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(db.phanloais.Where(n => n.ten_phanloai.Contains(searchString) || searchString == null).ToList().OrderBy(n => n.id_phanloai).ToPagedList(page ?? 1, 5));
           
        }


        //THEM MOI
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(phanloai pl)
        {
            db.phanloais.Add(pl);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        //Chi tiet phan loai
        public ActionResult Details(int? id)
        {
            phanloai pl = db.phanloais.SingleOrDefault(n => n.id_phanloai == id);
            if (pl == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(pl);
        }

        //xóa phan loai
        [HttpGet]
        public ActionResult Delete(int? id)
        {
            phanloai pl = db.phanloais.SingleOrDefault(n => n.id_phanloai == id);
            if (pl == null)
            {
                Response.StatusCode = 404;
                return null;
            }

            return View(pl);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            phanloai pl = db.phanloais.SingleOrDefault(n => n.id_phanloai == id);
            if (pl == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            db.phanloais.Remove(pl);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //Sua phan loai
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            phanloai pl = db.phanloais.SingleOrDefault(n => n.id_phanloai == id);
            if (pl == null)
            {
                Response.StatusCode = 404;
                return null;
            }

            return View(pl);
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(phanloai pl, FormCollection f)
        {
            if (ModelState.IsValid)
            {
                //Thuc hien cap nhat trong model
                db.Entry(pl).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

TRANGADMIN/WebShop/Areas/Admin/Views/QuanLyPhanLoai/Create.cshtml
@model WebShop.Models.phanloai

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Layout/_LayoutAdmin.cshtml";
}

<h2>Tạo mới phân loại</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
			<label class="control-label col-md-2" for="ten_phanloai">Tên phân loại</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.ten_phanloai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ten_phanloai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
			<label class="control-label col-md-2" for="ten_phanloai">Cùng loại</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.cungphanloai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cungphanloai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Tạo mới" class="btn btn-default" />
            </div>
        </div>
    </div>
}

	<div>
		@Html.ActionLink("Quay trở lại", "Index", "", new { @style = "color: black;padding:5px;font-weight: bold;", @class = "btn btn-default" })
	</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TRANGADMIN/WebShop/Areas/Admin/Views/QuanLyPhanLoai/Delete.cshtml
@model WebShop.Models.phanloai

@{
	ViewBag.Title = "Delete";
	Layout = "~/Views/Layout/_LayoutAdmin.cshtml";
}

<h2>Xóa phân loại</h2>

<h3>Bạn có chắc muốn xóa phân loại này</h3>
<div>
	<hr />
	<dl class="dl-horizontal">
		<dt>
			Tên phân loại
		</dt>

		<dd>
			@Html.DisplayFor(model => model.ten_phanloai)
		</dd>

		<dt>
			Cùng loại
		</dt>

		<dd>
			@Html.DisplayFor(model => model.cungphanloai)
		</dd>

	</dl>

	@using (Html.BeginForm())
	{
		@Html.AntiForgeryToken()

		<div class="form-actions no-color">
			<input type="submit" value="Xóa" class="btn btn-default" style="color:red;font-weight:bold;" /> |
			@Html.ActionLink("Quay trở lại", "Index", "", new { @style = "color: black;padding:5px;font-weight: bold;", @class = "btn btn-default" })
		</div>
	}
</div>

TRANGADMIN/WebShop/Areas/Admin/Views/QuanLyPhanLoai/Details.cshtml
@model WebShop.Models.phanloai

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Layout/_LayoutAdmin.cshtml";
}

<h2>Chi tiết phân loại</h2>

<div>
 
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Tên phân loại
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ten_phanloai)
        </dd>

        <dt>
           Cùng loại
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cungphanloai)
        </dd>

    </dl>
</div>
<p>
	@Html.ActionLink("Sửa", "Edit", new { id = Model.id_phanloai }, new { @style = "color: black;padding:5px;font-weight: bold;", @class = "btn btn-default" }) |
	@Html.ActionLink("Quay trở lại", "Index", "", new { @style = "color: black;padding:5px;font-weight: bold;", @class = "btn btn-default" })
</p>

TRANGADMIN/WebShop/Areas/Admin/Views/QuanLyPhanLoai/Edit.cshtml
@model WebShop.Models.phanloai

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Layout/_LayoutAdmin.cshtml";
}

<h2>Sửa phân loại</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id_phanloai)

        <div class="form-group">
			<label class="control-label col-md-2" for="ten_phanloai">Tên phân loại</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.ten_phanloai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ten_phanloai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
			<label class="control-label col-md-2" for="ten_phanloai">Cùng mặt hàng</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.cungphanloai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cungphanloai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-default" />
            </div>
        </div>
    </div>
}

	<div>
		@Html.ActionLink("Quay trở lại", "Index", "", new { @style = "color: black;padding:5px;font-weight: bold;", @class = "btn btn-default" })
	</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TRANGADMIN/WebShop/Areas/Admin/Views/QuanLyPhanLoai/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@model PagedList.PagedList<WebShop.Models.phanloai>
@using WebShop.Models;

@{
	ViewBag.Title = "Index";
	Layout = "~/Views/Layout/_LayoutAdmin.cshtml";
}

<h2>Phân loại</h2>

<button style="margin-bottom:20px;">
	@Html.ActionLink("Tạo sản phẩm mới", "Create", "", new { @style = "color: #da2a2a;font-weight:bold;" })
</button>
@using (Html.BeginForm("Index", "QuanLyPhanLoai", FormMethod.Get))
{
	@Html.TextBox("searchString")<input type="submit" value="Search" />
}
<table class="table">
	<tr>
		<th>
			Tên phân loại
		</th>

		<th></th>
	</tr>

	@foreach (var item in Model)
	{
		<tr>
			<td width="83%">
				@Html.DisplayFor(modelItem => item.ten_phanloai)
			</td>

			<td style="padding:5px;">
				@Html.ActionLink("Sửa", "Edit", new { id = item.id_phanloai }, new { @style = "color: black;padding:5px;font-weight: bold;", @class = "btn btn-default" })
				@Html.ActionLink("Chi tiết", "Details", new { id = item.id_phanloai }, new { @style = "color: black;padding:5px;font-weight: bold;", @class = "btn btn-default" })
				@Html.ActionLink("Xóa", "Delete", new { id = item.id_phanloai }, new { @style = "color: red;padding:5px;font-weight: bold;", @class = "btn btn-default" })
			</td>
		</tr>
	}

</table>
<h7>Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/ @Model.PageCount</h7>
<div class="MenuTrang">
	@Html.PagedListPager(Model, page => Url.Action("Index", "QuanLyPhanloai", new { page, searchString = Request.QueryString["searchString"] }))
</div>
<style>
	.MenuTrang li {
		display: inline;
	}
</style>