TRANGADMIN/WebShop/Areas/Admin/Controllers/QuanLyProductController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebShop.Models;

namespace WebShop.Areas.Admin.Controllers
{
    public class QuanLyProductController : Controller
    {
        thoitrangnamEntities4 db = new thoitrangnamEntities4();
        // GET: Admin/QuanLyProduct
        public ActionResult Index(string searchString,int? page)
        {
            // int pageSize = 5;
            // int pageNumber = (page ?? 1);
            //return View(db.sanphams.ToList().OrderBy(n => n.id).ToPagedList(pageNumber, pageSize));
            List<user> lstKq = db.users.ToList();
            return View(db.sanphams.Where(n => n.ten_sp.Contains(searchString) || searchString == null).ToList().ToPagedList(page ?? 1, 9));
        }

        //THEM MOI
        [HttpGet]
        public ActionResult Create()
        {
            //đưa dữ liệu vào dropdown list ten_chatlieu	ten_loaihang	ten_mau	ten_phanloai
            ViewBag.id_loaihang = new SelectList(db.loaihangs.ToList().OrderBy(n => n.ten_loaihang), "id_loaihang", "ten_loaihang");
            ViewBag.id_phanloai = new SelectList(db.phanloais.ToList().OrderBy(n => n.ten_phanloai), "id_phanloai", "ten_phanloai");
            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(sanpham sp)
        {
            
            db.sanphams.Add(sp);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        //Chi tiet sp
        public ActionResult Details(int? id)
        {
            sanpham sp = db.sanphams.SingleOrDefault(n => n.id == id);
            if (sp == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(sp);
        }

        //xóa sp
        [HttpGet]
        public ActionResult Delete(int? id)
        {
            sanpham sp = db.sanphams.SingleOrDefault(n => n.id == id);
            if (sp == null)
            {
                Response.StatusCode = 404;
                return null;
            }

            return View(sp);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            sanpham sp = db.sanphams.SingleOrDefault(n => n.id == id);
            if (sp == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            db.sanphams.Remove(sp);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //Sua sp
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            //đưa dữ liệu vào dropdown list ten_chatlieu	ten_loaihang	ten_mau	ten_phanloai
            ViewBag.id_loaihang = new SelectList(db.loaihangs.ToList().OrderBy(n => n.ten_loaihang), "id_loaihang", "ten_loaihang");
            ViewBag.id_phanloai = new SelectList(db.phanloais.ToList().OrderBy(n => n.ten_phanloai), "id_phanloai", "ten_phanloai");
            sanpham sp = db.sanphams.SingleOrDefault(n => n.id == id);
            if (sp == null)
            {
                Response.StatusCode = 404;
                return null;
            }

            return View(sp);
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(sanpham sp, FormCollection f)
        {
            if (ModelState.IsValid)
            {
                //Thuc hien cap nhat trong model
                db.Entry(sp).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

TRANGADMIN/WebShop/Areas/Admin/Views/QuanLyProduct/Create.cshtml
@model WebShop.Models.sanpham
@using WebShop.Models;
@{
	ViewBag.Title = "Create";
	Layout = "~/Views/Layout/_LayoutAdmin.cshtml";
}
<script src="~/Areas/Admin/assets/ckeditor/ckeditor.js"></script>
@section jsFooter{
	<script>
		$('#btnSelectImage').on('click', function (e) {
			e.preventDefault();
			var finder = new CKFinder();
			finder.selectActionFunction = function (url) {
				$('#txtImage').val(url);
			};
			finder.popup();
		})
	</script>
}

@{
	var session = (user)Session["Taikhoan"];
}
@if (session != null)
{
	<h2>Thêm sản phẩm</h2>
	using (Html.BeginForm())
	{
		@Html.AntiForgeryToken()

		<div class="form-horizontal">

			<hr />
			<div class="form-group">
				<p class="control-label col-md-2">Giống nhau</p>
				<div class="col-md-10">
					@Html.EditorFor(model => model.giongnhau, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.giongnhau, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				<p class="control-label col-md-2">ID loại hàng</p>
				<div class="col-md-10">
					@Html.DropDownList("id_loaihang", null, htmlAttributes: new { @class = "form-control" })
					@Html.ValidationMessageFor(model => model.id_loaihang, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				<p class="control-label col-md-2">ID phân loại</p>
				<div class="col-md-10">
					@Html.DropDownList("id_phanloai", null, htmlAttributes: new { @class = "form-control" })
					@Html.ValidationMessageFor(model => model.id_phanloai, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				<p class="control-label col-md-2">Tên sản phẩm</p>
				<div class="col-md-10">
					@Html.EditorFor(model => model.ten_sp, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.ten_sp, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				<p class="control-label col-md-2">Giá</p>
				<div class="col-md-10">
					@Html.EditorFor(model => model.gia, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.gia, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				<p class="control-label col-md-2">Giảm giá</p>
				<div class="col-md-10">
					@Html.EditorFor(model => model.phantramgiamgia, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.phantramgiamgia, "", new { @class = "text-danger" })
				</div>
			</div>



			<div class="form-group">
				<p class="control-label col-md-2">Size</p>
				<div class="col-md-10">
					@Html.EditorFor(model => model.size, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.size, "", new { @class = "text-danger" })
				</div>
			</div>
			<div class="form-group">
				<p class="control-label col-md-2">Số lượng</p>
				<div class="col-md-10">
					@Html.EditorFor(model => model.soluonng, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.soluonng, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				<p class="control-label col-md-2">Màu sắc</p>
				<div class="col-md-10">
					@Html.EditorFor(model => model.mo_ta_mau_sac, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.mo_ta_mau_sac, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				<p class="control-label col-md-2">Hình ảnh</p>
				<div class="col-md-10">
					@Html.EditorFor(model => model.hinh_anh, new { htmlAttributes = new { @class = "form-control", @id = "txtImage" }, id = "txtImage" })
					<a id="btnSelectImage" href="#">Chọn hình ảnh</a>
					@Html.ValidationMessageFor(model => model.hinh_anh, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				<p class="control-label col-md-2">Kiểu dáng</p>
				<div class="col-md-10">
					@Html.TextAreaFor(model => model.mo_ta_kieu_dang, new { htmlAttributes = new { @class = "form-control", @id = "txtMota" }, id = "txtMota" })
					<script type="text/javascript">
						CKEDITOR.replace("txtMota");
					</script>
				</div>
			</div>

			<div class="form-group">
				<div class="col-md-offset-2 col-md-10">
					<input type="submit" value="Tạo mới" class="btn btn-default" />
				</div>
			</div>
		</div>
	}

		<div>
			@Html.ActionLink("Quay trở lại", "Index", "", new { @style = "color: black;padding:5px;font-weight: bold;", @class = "btn btn-default" })
		</div>
}
else
{
	<h2>Bạn chưa đăng nhập</h2>
	<a href="@Url.Action("Login","Login")">
		<p style="padding-bottom: 29px;color: blue;text-decoration: underline;">Trở lại đăng nhập</p>
	</a>
}

TRANGADMIN/WebShop/Areas/Admin/Views/QuanLyProduct/Delete.cshtml
@model WebShop.Models.sanpham
@using WebShop.Models;
@{
	ViewBag.Title = "Delete";
	Layout = "~/Views/Layout/_LayoutAdmin.cshtml";
}

@{
	var session = (user)Session["Taikhoan"];
}
@if (session != null)
{
	<h2>Xóa sản phẩm</h2>
	<h3>Bạn có chắc muốn xóa sản phẩm này</h3>
	<div>
		<hr />
		<dl class="dl-horizontal">

			<dt>
				Tên sản phẩm
			</dt>

			<dd>
				@Html.DisplayFor(model => model.ten_sp)
			</dd>

			<dt>
				Giá
			</dt>

			<dd>
				@Html.DisplayFor(model => model.gia)
			</dd>

			<dt>
				%Sale
			</dt>

			<dd>
				@Html.DisplayFor(model => model.phantramgiamgia)
			</dd>



			<dt>
				Size
			</dt>

			<dd>
				@Html.DisplayFor(model => model.size)
			</dd>

			<dt>
				Màu sắc
			</dt>

			<dd>
				@Html.DisplayFor(model => model.mo_ta_mau_sac)
			</dd>




			<dt>
				Số lượng
			</dt>

			<dd>
				@Html.DisplayFor(model => model.soluonng)
			</dd>

			<dt>
				Loại hàng
			</dt>

			<dd>
				@Html.DisplayFor(model => model.loaihang.ten_loaihang)
			</dd>


			<dt>
				Phân loại
			</dt>

			<dd>
				@Html.DisplayFor(model => model.phanloai.ten_phanloai)
			</dd>

		</dl>

		@using (Html.BeginForm())
		{
			@Html.AntiForgeryToken()

		<div class="form-actions no-color">
			<input type="submit" value="Xóa" class="btn btn-default" style="color:red;font-weight:bold;" /> |
			@Html.ActionLink("Quay trở lại", "Index", "", new { @style = "color: black;padding:5px;font-weight: bold;", @class = "btn btn-default" })
		</div>
		}
	</div>
}
else
{
	<h2>Bạn chưa đăng nhập</h2>
	<a href="@Url.Action("Login","Login")">
		<p style="padding-bottom: 29px;color: blue;text-decoration: underline;">Trở lại đăng nhập</p>
	</a>
}

TRANGADMIN/WebShop/Areas/Admin/Views/QuanLyProduct/Details.cshtml
@model WebShop.Models.sanpham
@using WebShop.Models;
@{
	ViewBag.Title = "Chi tiết sản phẩm";
	Layout = "~/Views/Layout/_LayoutAdmin.cshtml";
}


@{
	var session = (user)Session["Taikhoan"];
}
@if (session != null)
{
	<h2>Chi tiết sản phẩm</h2>
	<div>

		<hr />
		<dl class="dl-horizontal">

			<dt>
				Tên sản phẩm
			</dt>

			<dd>
				@Html.DisplayFor(model => model.ten_sp)
			</dd>

			<dt>
				Giá
			</dt>

			<dd>
				@Html.DisplayFor(model => model.gia)
			</dd>

			<dt>
				%Sale
			</dt>

			<dd>
				@Html.DisplayFor(model => model.phantramgiamgia)
			</dd>



			<dt>
				Size
			</dt>

			<dd>
				@Html.DisplayFor(model => model.size)
			</dd>



			<dt>
				Màu sắc
			</dt>

			<dd>
				@Html.DisplayFor(model => model.mo_ta_mau_sac)
			</dd>





			<dt>
				Số lượng
			</dt>

			<dd>
				@Html.DisplayFor(model => model.soluonng)
			</dd>

			<dt>
				Loại hàng
			</dt>

			<dd>
				@Html.DisplayFor(model => model.loaihang.ten_loaihang)
			</dd>


			<dt>
				Phân loại
			</dt>

			<dd>
				@Html.DisplayFor(model => model.phanloai.ten_phanloai)
			</dd>

		</dl>
	</div>
	<p>
		@Html.ActionLink("Sửa", "Edit", new { id = Model.id }, new { @style = "color: black;padding:5px;font-weight: bold;", @class = "btn btn-default" }) |
		@Html.ActionLink("Quay trở lại", "Index", "", new { @style = "color: black;padding:5px;font-weight: bold;", @class = "btn btn-default" })
	</p>
}
else
{
	<h2>Bạn chưa đăng nhập</h2>
	<a href="@Url.Action("Login","Login")">
		<p style="padding-bottom: 29px;color: blue;text-decoration: underline;">Trở lại đăng nhập</p>
	</a>
}

TRANGADMIN/WebShop/Areas/Admin/Views/QuanLyProduct/Edit.cshtml
@model WebShop.Models.sanpham
@using WebShop.Models;
@{
	ViewBag.Title = "Edit";
	Layout = "~/Views/Layout/_LayoutAdmin.cshtml";
}
<script src="~/Areas/Admin/assets/ckeditor/ckeditor.js"></script>
@section jsFooter{
	<script>
		$('#btnSelectImage').on('click', function (e) {
			e.preventDefault();
			var finder = new CKFinder();
			finder.selectActionFunction = function (url) {
				$('#txtImage').val(url);
			};
			finder.popup();
		})
	</script>
}
@{
	var session = (user)Session["Taikhoan"];
}
@if (session != null)
{
	<h2>Chỉnh sửa sản phẩm</h2>
	using (Html.BeginForm())
	{
		@Html.AntiForgeryToken()

		<div class="form-horizontal">

			<hr />
			@Html.ValidationSummary(true, "", new { @class = "text-danger" })
			@Html.HiddenFor(model => model.id)

			<div class="form-group">
				<p class="control-label col-md-2">Giống nhau</p>
				<div class="col-md-10">
					@Html.EditorFor(model => model.giongnhau, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.giongnhau, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				<p class="control-label col-md-2">ID loại hàng</p>
				<div class="col-md-10">
					@Html.DropDownList("id_loaihang", null, htmlAttributes: new { @class = "form-control" })
					@Html.ValidationMessageFor(model => model.id_loaihang, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				<p class="control-label col-md-2">ID phân loại</p>
				<div class="col-md-10">
					@Html.DropDownList("id_phanloai", null, htmlAttributes: new { @class = "form-control" })
					@Html.ValidationMessageFor(model => model.id_phanloai, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				<p class="control-label col-md-2">Tên sản phẩm</p>
				<div class="col-md-10">
					@Html.EditorFor(model => model.ten_sp, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.ten_sp, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				<p class="control-label col-md-2">Giá</p>
				<div class="col-md-10">
					@Html.EditorFor(model => model.gia, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.gia, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				<p class="control-label col-md-2">Giảm giá</p>
				<div class="col-md-10">
					@Html.EditorFor(model => model.phantramgiamgia, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.phantramgiamgia, "", new { @class = "text-danger" })
				</div>
			</div>



			<div class="form-group">
				<p class="control-label col-md-2">Size</p>
				<div class="col-md-10">
					@Html.EditorFor(model => model.size, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.size, "", new { @class = "text-danger" })
				</div>
			</div>
			<div class="form-group">
				<p class="control-label col-md-2">Số lượng</p>
				<div class="col-md-10">
					@Html.EditorFor(model => model.soluonng, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.soluonng, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				<p class="control-label col-md-2">Màu sắc</p>
				<div class="col-md-10">
					@Html.EditorFor(model => model.mo_ta_mau_sac, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.mo_ta_mau_sac, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				<p class="control-label col-md-2">Hình ảnh</p>
				<div class="col-md-10">
					@Html.EditorFor(model => model.hinh_anh, new { htmlAttributes = new { @class = "form-control", @id = "txtImage" }, id = "txtImage" })
					<a id="btnSelectImage" href="#">Chọn hình ảnh</a>
					@Html.ValidationMessageFor(model => model.hinh_anh, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				<p class="control-label col-md-2">Kiểu dáng</p>
				<div class="col-md-10">
					@Html.TextAreaFor(model => model.mo_ta_kieu_dang, new { htmlAttributes = new { @class = "form-control", @id = "txtMota" }, id = "txtMota" })
					<script type="text/javascript">
						CKEDITOR.replace("txtMota");
					</script>
				</div>
			</div>

			<div class="form-group">
				<div class="col-md-offset-2 col-md-10">
					<input type="submit" value="Lưu" class="btn btn-default" />
				</div>
			</div>
		</div>
	}

		<div>
			@Html.ActionLink("Quay trở lại", "Index", "", new { @style = "color: black;padding:5px;font-weight: bold;", @class = "btn btn-default" })
		</div>

	@section Scripts {
		@Scripts.Render("~/bundles/jqueryval")
	}
}
else
{
	<h2>Bạn chưa đăng nhập</h2>
	<a href="@Url.Action("Login","Login")">
		<p style="padding-bottom: 29px;color: blue;text-decoration: underline;">Trở lại đăng nhập</p>
	</a>
}

TRANGADMIN/WebShop/Areas/Admin/Views/QuanLyProduct/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@model PagedList.PagedList<WebShop.Models.sanpham>
@using WebShop.Models;

@{
	/**/

	ViewBag.Title = "Index";
	Layout = "~/Views/Layout/_LayoutAdmin.cshtml";
}

@{
	var session = (user)Session["Taikhoan"];
}
@if (session != null)
{
	<h2 style="
    font-weight: initial;
">Quản lý sản phẩm</h2>
	<button style="margin-bottom:20px;">
		@Html.ActionLink("Tạo sản phẩm mới", "Create", "",new { @style = "color: #da2a2a;font-weight:bold;" })
	</button>
	<br />
	using (Html.BeginForm("Index", "QuanLyProduct", FormMethod.Get))
	{
		@Html.TextBox("searchString")<input type="submit" value="Search" />
	}
	<br />

	<table class="table table-striped">
		<tr>

			<th>
				Tên sản phẩm
			</th>
			<th>
				Giá
			</th>
			<th>
				%Sale
			</th>

			<th>
				Size
			</th>
			<th>
				Màu sắc
			</th>

			<th>
				Số lượng
			</th>

			<th>
				Loại hàng
			</th>

			<th>
				Phân loại
			</th>

			<th></th>
		</tr>

		@foreach (var item in Model)
		{
			<tr>

				<td>
					@Html.DisplayFor(modelItem => item.ten_sp)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.gia)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.phantramgiamgia)
				</td>

				<td>
					@Html.DisplayFor(modelItem => item.size)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.mo_ta_mau_sac)
				</td>

				<td>
					@Html.DisplayFor(modelItem => item.soluonng)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.loaihang.ten_loaihang)
				</td>

				<td>
					@*k hien thi html*@
					@Html.Raw(item.mo_ta_kieu_dang)
				</td>
				<td style="width:195px;">
					@Html.ActionLink("Sửa", "Edit", new { id = item.id }, new { @style = "color: black;padding:5px;font-weight: bold;", @class = "btn btn-default" }) 
					@Html.ActionLink("Chi tiết", "Details", new { id = item.id }, new { @style = "color: black;padding:5px;font-weight: bold;", @class = "btn btn-default" }) 
					@Html.ActionLink("Xóa", "Delete", new { id = item.id }, new { @style = "color: red;padding:5px;font-weight: bold;", @class = "btn btn-default" })
				</td>
			</tr>
		}

	</table>
}
else
{
	<h2>Bạn chưa đăng nhập</h2>
	<a href="@Url.Action("Login","Login")">
		<p style="padding-bottom: 29px;color: blue;text-decoration: underline;">Trở lại đăng nhập</p>
	</a>
}
@*Tạo link liên kết các trang*@
@if (session != null)
{
	<h7>Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/ @Model.PageCount</h7>
	<div class="MenuTrang">
		@Html.PagedListPager(Model, page => Url.Action("Index", "QuanLyProduct", new { page, searchString = Request.QueryString["searchString"] }))
	</div>
	<style>
		.MenuTrang li {
			display: inline;
		}
	</style>

}
else
{
}