TRANGADMIN/WebShop/Models/phanhoi.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class phanhoi
    {
        public int idphanhoi { get; set; }
        public string email { get; set; }
        public Nullable<int> idstatusgui { get; set; }
        public string noidung { get; set; }
        public string noidungphanhoi { get; set; }
        public string tieude { get; set; }
        public Nullable<System.DateTime> ngaygui { get; set; }
    
        public virtual statusphanhoi statusphanhoi { get; set; }
    }
}

TRANGADMIN/WebShop/Areas/Admin/Controllers/PhanhoiController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebShop.Models;
using WebShop.Areas.Admin.Models;
using System.Net.Mail;
using System.Net;

namespace WebShop.Areas.Admin.Controllers
{
	public class PhanhoiController : Controller
	{
		thoitrangnamEntities4 db = new thoitrangnamEntities4();
		// GET: Admin/Contact
		public ActionResult Index(string searchString, int? page)
		{
			int pageSize = 5;
			int pageNumber = (page ?? 1);
			return View(db.phanhois.Where(n => n.tieude.Contains(searchString) || searchString == null).ToList().OrderByDescending(n => n.ngaygui).ToPagedList(pageNumber, pageSize));

		}

		//Chi tiet contact
		public ActionResult Details(int? id)
		{
			phanhoi ph = db.phanhois.SingleOrDefault(n => n.idphanhoi == id);
			if (ph == null)
			{
				Response.StatusCode = 404;
				return null;
			}
			return View(ph);
		}

		//xóa contact
		[HttpGet]
		public ActionResult Delete(int? id)
		{
			phanhoi ph = db.phanhois.SingleOrDefault(n => n.idphanhoi == id);
			if (ph == null)
			{
				Response.StatusCode = 404;
				return null;
			}

			return View(ph);
		}

		[HttpPost, ActionName("Delete")]
		public ActionResult Delete(int id)
		{
			phanhoi ph = db.phanhois.SingleOrDefault(n => n.idphanhoi == id);
			if (ph == null)
			{
				Response.StatusCode = 404;
				return null;
			}
			db.phanhois.Remove(ph);
			db.SaveChanges();
			return RedirectToAction("Index");
		}

		//Sua mail
		[HttpGet]
		public ActionResult Edit(int? id)
		{
			ViewBag.idstatusgui = new SelectList(db.statusphanhois.ToList().OrderBy(n => n.status), "id", "status");
			phanhoi ph = db.phanhois.SingleOrDefault(n => n.idphanhoi == id);
			if (ph == null)
			{
				Response.StatusCode = 404;
				return null;
			}

			return View(ph);
		}
		[HttpPost]
		[ValidateInput(false)]
		public ActionResult Edit(phanhoi ph, FormCollection f)
		{
			if (ModelState.IsValid)
			{
				//thuc hien gui mail
				MailMessage mm = new MailMessage("cskhbrazza123@gmail.com", ph.email);
				mm.Subject = ph.tieude;
				mm.Body = ph.noidungphanhoi.ToString();
				mm.IsBodyHtml = true;

				SmtpClient smtp = new SmtpClient();
				smtp.Host = "smtp.gmail.com";
				smtp.Port = 587;
				smtp.EnableSsl = true;

				NetworkCredential nc = new NetworkCredential("cskhbrazza123@gmail.com", "cskh123456");
				smtp.UseDefaultCredentials = true;
				smtp.Credentials = nc;
				smtp.Send(mm);
				// thay doi thanh da tra loi
				ph.idstatusgui = 2;

				//Thuc hien cap nhat trong model
				db.Entry(ph).State = System.Data.Entity.EntityState.Modified;
				db.SaveChanges();
			}
			return RedirectToAction("Index");
		}
	}
}

TRANGADMIN/WebShop/Areas/Admin/Views/Phanhoi/Delete.cshtml
@model WebShop.Models.phanhoi

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Layout/_LayoutAdmin.cshtml";
}

<h2>Xóa phản hồi</h2>

<h3>Bạn có chắc làm muốn xóa phản hồi</h3>
<div>
    <hr />
	<dl class="dl-horizontal">
		<dt>
			Email của khách hàng
		</dt>

		<dd>
			@Html.DisplayFor(model => model.email)
		</dd>

		<dt>
			Nội dung của khách hàng
		</dt>

		<dd>
			@Html.DisplayFor(model => model.noidung)
		</dd>

		<dt>
			Nội dung của shop
		</dt>

		<dd>
			@Html.Raw(Model.noidungphanhoi)
		</dd>

		<dt>
			Tiêu đề của shop
		</dt>

		<dd>
			@Html.DisplayFor(model => model.tieude)
		</dd>

		<dt>
			Ngày gửi phản hồi
		</dt>

		<dd>
			@Html.DisplayFor(model => model.ngaygui)
		</dd>

		<dt>
			Trạng thái
		</dt>

		<dd>
			@Html.DisplayFor(model => model.statusphanhoi.status)
		</dd>

	</dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

	<div class="form-actions no-color">
		<input type="submit" value="Xóa" class="btn btn-default" style="color:red; font-weight:bold" /> |
		@Html.ActionLink("Quay trở lại", "Index","", new { @style = "color: black;padding:5px;font-weight: bold;", @class = "btn btn-default" })
	</div>
    }
</div>

TRANGADMIN/WebShop/Areas/Admin/Views/Phanhoi/Details.cshtml
@model WebShop.Models.phanhoi

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Layout/_LayoutAdmin.cshtml";
}

<h2>Chi tiết phản hồi</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Email của khách hàng
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            Nội dung của khách hàng
        </dt>

        <dd>
            @Html.DisplayFor(model => model.noidung)
        </dd>

        <dt>
           Nội dung của shop
        </dt>

        <dd>
            @Html.Raw(Model.noidungphanhoi)
        </dd>

        <dt>
            Tiêu đề của shop
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tieude)
        </dd>

        <dt>
            Ngày gửi phản hồi
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ngaygui)
        </dd>

        <dt>
            Trạng thái
        </dt>

        <dd>
            @Html.DisplayFor(model => model.statusphanhoi.status)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Sửa", "Edit", new { id = Model.idphanhoi }, new { @style = "color: black;padding:5px;font-weight: bold;", @class = "btn btn-default" }) |
    @Html.ActionLink("Quay trở lại", "Index","", new { @style = "color: black;padding:5px;font-weight: bold;", @class = "btn btn-default" })
</p>

TRANGADMIN/WebShop/Areas/Admin/Views/Phanhoi/Edit.cshtml
@model WebShop.Models.phanhoi

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Layout/_LayoutAdmin.cshtml";
}
<script src="~/Areas/Admin/assets/ckeditor/ckeditor.js"></script>
<h2>Gửi phản hồi cho khách hàng</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.idphanhoi)

        <div class="form-group">
			<label class="control-label col-md-2" for="email">Email khách hàng</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
			<label class="control-label col-md-2" for="email">Trạng thái</label>
            <div class="col-md-10">
                @Html.DropDownList("idstatusgui", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idstatusgui, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
			<label class="control-label col-md-2" for="email">Nội dung phản hồi của khách hàng</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.noidung, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.noidung, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
			<label class="control-label col-md-2" for="email">Tiêu đề phản hồi của shop</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.tieude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tieude, "", new { @class = "text-danger" })
            </div>
        </div>
		<div class="form-group">
			<label class="control-label col-md-2" for="email">Nội dung phản hồi của shop</label>
			<div class="col-md-10">
				@Html.TextAreaFor(model => model.noidungphanhoi, new { htmlAttributes = new { @class = "form-control", @id = "txtReply" }, id = "txtReply" })
				<script type="text/javascript">
                    CKEDITOR.replace("txtReply");
				</script>
			</div>
		</div>

        <div class="form-group">
			<label class="control-label col-md-2" for="email">Ngày phản hồi cho khách hàng</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.ngaygui, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ngaygui, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-default" />
            </div>
        </div>
    </div>
}

	<div>
		@Html.ActionLink("Quay trở lại", "Index", "", new { @style = "color: black;padding:5px;font-weight: bold;", @class = "btn btn-default" })
	</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TRANGADMIN/WebShop/Areas/Admin/Views/Phanhoi/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@model PagedList.PagedList<WebShop.Models.phanhoi>
@{
	ViewBag.Title = "Index";
	Layout = "~/Views/Layout/_LayoutAdmin.cshtml";
}

<h2>Phản hồi của khách hàng</h2>
@using (Html.BeginForm("Index", "Phanhoi", FormMethod.Get))
	{
@Html.TextBox("searchString")<input type="submit" value="Search" />
	}
<table class="table">
	<tr>
		<th>
			Email khách hàng
		</th>
		<th>
			Nội dung của khách hàng
		</th>
		<th>
			Nội dung phản hồi
		</th>
		<th>
			Tiêu đề
		</th>
		<th>
			Ngày gửi
		</th>
		<th>
			Trạng thái
		</th>
		<th></th>
	</tr>

	@foreach (var item in Model)
	{
		<tr>
			<td>
				@Html.DisplayFor(modelItem => item.email)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.noidung)
			</td>
			<td>
				@Html.Raw(item.noidungphanhoi)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.tieude)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.ngaygui)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.statusphanhoi.status)
			</td>
			<td style="width:195px;">
				@Html.ActionLink("Sửa", "Edit", new { id = item.idphanhoi }, new { @style = "color: black;padding:5px;font-weight: bold;", @class = "btn btn-default" })
				@Html.ActionLink("Chi tiết", "Details", new { id = item.idphanhoi }, new { @style = "color: black;padding:5px;font-weight: bold;", @class = "btn btn-default" })
				@Html.ActionLink("Xóa", "Delete", new { id = item.idphanhoi }, new { @style = "color: red;padding:5px;font-weight: bold;", @class = "btn btn-default" })
			</td>
		</tr>
	}

</table>
<h7>Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/ @Model.PageCount</h7>
<div class="MenuTrang">
	@Html.PagedListPager(Model, page => Url.Action("Index", "Phanhoi", new { page, searchString = Request.QueryString["searchString"] }))
</div>
<style>
	.MenuTrang li {
		display: inline;
	}
</style>